version: '3.5'

services:

  mysql:
    image: mysql:5.7
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'batch_employee'
      MYSQL_ROOT_PASSWORD: 's3cr3t'
    ports:
      - "3307:3306"

  batch-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    depends_on:
      - "mysql"
    ports:
      - '8083:8080'