version: '3.5'

services:

  mysql:
    image: mysql:5.7
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'batch_employee'
      MYSQL_ROOT_PASSWORD: 's3cr3t'
    ports:
      - "3307:3306"

  batch-app:
    environment:
      # Utilizar HOST = host.docker.internal em MacOs, Windows
      # Utilizar HOST = <sudo ip addr show docker0> em Linux
      - DATABASE_HOST=172.17.0.1
      - DATABASE_PORT=3307
      - DATABASE_SCHEMA=todolist
      - DATABASE_USER=root
      - DATABASE_PASSWORD=s3cr3t
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    ports:
      - '8083:8080'