INSERT INTO CADASTRO (ID, NOME, DT_CRIACAO) VALUES (1, 'ZE COLMEIA', now());
INSERT INTO CADASTRO (ID, NOME, DT_CRIACAO) VALUES (2, 'CATATAU', now());
INSERT INTO CADASTRO (ID, NOME, DT_CRIACAO) VALUES (3, 'SCOOBDOO', now());
INSERT INTO CADASTRO (ID, NOME, DT_CRIACAO) VALUES (4, 'Leonardo', now());
INSERT INTO CADASTRO (ID, NOME, DT_CRIACAO) VALUES (5, 'Rafael', now());
INSERT INTO CADASTRO (ID, NOME, DT_CRIACAO) VALUES (6, 'Michelangelo', now());
INSERT INTO CADASTRO (ID, NOME, DT_CRIACAO) VALUES (7, 'Donatello', now());